In [ ]:
import pandas as pd
df=pd.read_excel("pandas_01_day6.xlsx")

In [ ]:
df.shape

(87, 3)

In [6]:
df.describe()

        Height  Weight Favourite Dish
count     87.0      87             87
unique    35.0      47              5
top        5.9      55        Biryani
freq       9.0       6             40

In [5]:
df.T

,0,1,2,3,4,5,6,7,8,9,...,77,78,79,80,81,82,83,84,85,86
Height,5.8,6.2,5.9,5.9,5.9,5.3,5.6,5.9,5.1,5.4,...,5.5,5’11,5'3,5.4,5.5,5.4,5.9,5.4,6.2,5.1
Weight,101,92,62,95,55,59,50,76,78,68,...,85,72,62,55,52,55,75KG,61,68,96
Favourite Dish,Chicken Pulao,Biryani,Karahi Ghosht,Chicken Pulao,Chicken Pulao,Biryani,Pasta,Biryani,Biryani,Biryani,...,Biryani,Karahi Ghosht,Biryani,Pasta,Karahi Ghosht,Pasta,Karahi Ghosht,Biryani,Chicken Pulao,Biryani

In [ ]:
df.rename

In [3]:
import numpy as np
# numpy array DataFrame
pd.DataFrame(np.random.rand(5, 9))

,0,1,2,3,4,5,6,7,8
0,0.294635,0.002380,0.002734,0.783125,0.667800,0.867515,0.573640,0.356033,0.317937
1,0.798736,0.135005,0.906003,0.009746,0.691343,0.061427,0.186758,0.024103,0.687366
2,0.939216,0.655115,0.800931,0.388438,0.997392,0.917192,0.913771,0.851809,0.647008
3,0.761074,0.367118,0.003718,0.079029,0.188675,0.109511,0.269516,0.223781,0.626758
4,0.586661,0.010138,0.847759,0.454267,0.961368,0.359034,0.776316,0.915644,0.401046

In [15]:
df=pd.DataFrame({'A col':[1,2,3,4,5,6,7,8], 'B col':[4,5,6,5,4,3,2,1]})
df

   A col  B col
0      1      4
1      2      5
2      3      6
3      4      5
4      5      4
5      6      3
6      7      2
7      8      1

In [4]:
import numpy as np
# numpy array use to create DataFrame
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
df=pd.DataFrame(arr)
df

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [4]:
# np array dataframe
pd.DataFrame(np.random.rand(4,8))

,0,1,2,3,4,5,6,7
0,0.447208,0.113421,0.910232,0.115794,0.492682,0.947837,0.256261,0.449782
1,0.797843,0.864851,0.932360,0.066358,0.649082,0.080393,0.905285,0.361388
2,0.444817,0.030613,0.927200,0.082332,0.520659,0.432668,0.032694,0.941471
3,0.130051,0.595709,0.318341,0.878098,0.931171,0.242849,0.967872,0.728560

In [6]:
pd.DataFrame(np.random.rand(4,8),columns=['a','b','c','d','e','f','g','h'])

,a,b,c,d,e,f,g,h
0,0.901423,0.854017,0.178606,0.598030,0.399226,0.063153,0.892272,0.242177
1,0.359752,0.955884,0.490284,0.135924,0.292093,0.569171,0.396161,0.062443
2,0.380447,0.814292,0.251617,0.999237,0.027730,0.116059,0.260009,0.649117
3,0.910773,0.472409,0.117208,0.645221,0.673248,0.429270,0.886895,0.506821

In [7]:
df=pd.DataFrame({'A col':[1,2,3,4,5,6,7,8], 'B col':[4,5,6,5,4,3,2,1]})
df

   A col  B col
0      1      4
1      2      5
2      3      6
3      4      5
4      5      4
5      6      3
6      7      2
7      8      1

In [5]:
df.rename(columns={'A col':'A','B col':'B'},inplace=True)
df

   Height Weight Favourite Dish
0     5.8    101  Chicken Pulao
1     6.2     92        Biryani
2     5.9     62  Karahi Ghosht
3     5.9     95  Chicken Pulao
4     5.9     55  Chicken Pulao
..    ...    ...            ...
82    5.4     55          Pasta
83    5.9   75KG  Karahi Ghosht
84    5.4     61        Biryani
85    6.2     68  Chicken Pulao
86    5.1     96        Biryani

[87 rows x 3 columns]

In [7]:
# adding prefix to columns
df=df.add_prefix('baba_')
df

   baba_A  baba_B
0       1       4
1       2       5
2       3       6
3       4       5
4       5       4
5       6       3
6       7       2
7       8       1

In [8]:
df.columns=['A','B']
df

   A  B
0  1  4
1  2  5
2  3  6
3  4  5
4  5  4
5  6  3
6  7  2
7  8  1

In [10]:
import seaborn as sns
tips=sns.load_dataset('tips')
tips.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [11]:
# summary of data
tips.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

# CSV & Excel

In [12]:
# saving a dataset
tips.to_csv('tips.csv')
tips.to_excel('tips.xlsx')

In [6]:
df=pd.read_csv('tips.csv')
df.head()

   Unnamed: 0  total_bill   tip     sex smoker  day    time  size
0           0       16.99  1.01  Female     No  Sun  Dinner     2
1           1       10.34  1.66    Male     No  Sun  Dinner     3
2           2       21.01  3.50    Male     No  Sun  Dinner     3
3           3       23.68  3.31    Male     No  Sun  Dinner     2
4           4       24.59  3.61  Female     No  Sun  Dinner     4

# 2-Reverse Row Order

In [37]:
df=sns.load_dataset('titanic')  
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [8]:
df.loc[::-1].head()

   A col  B col
7      8      1
6      7      2
5      6      3
4      5      4
3      4      5

In [9]:
df.loc[::-1].reset_index(drop=True).head()

   A col  B col
0      8      1
1      7      2
2      6      3
3      5      4
4      4      5

# Reverse column order

In [40]:
df.loc[:,::-1].head()

,alone,alive,embark_town,deck,adult_male,who,class,embarked,fare,parch,sibsp,age,sex,pclass,survived
0,False,no,Southampton,NaN,True,man,Third,S,7.2500,0,1,22.0,male,3,0
1,False,yes,Cherbourg,C,False,woman,First,C,71.2833,0,1,38.0,female,1,1
2,True,yes,Southampton,NaN,False,woman,Third,S,7.9250,0,0,26.0,female,3,1
3,False,yes,Southampton,C,False,woman,First,S,53.1000,0,1,35.0,female,1,1
4,True,no,Southampton,NaN,True,man,Third,S,8.0500,0,0,35.0,male,3,0

# Select a column by dtype

In [10]:
df.dtypes

A col    int64
B col    int64
dtype: object

In [11]:
#ONLY SELECT THOSE WHO HAVE NUMERIC VALUES
df.select_dtypes(include=[np.number]).head()

   A col  B col
0      1      4
1      2      5
2      3      6
3      4      5
4      5      4

In [12]:
#ONLY SELECT THOSE WHO HAVE NUMERIC and float values
df.select_dtypes(include=['object']).head()

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

# convert string to numbers

In [13]:
df=pd.DataFrame({'A col':['1','2','3','4','5','6','7','8'], 'B col':['4','5','6','5','4','3','2','1']}) 
df.dtypes

A col    object
B col    object
dtype: object

In [14]:
df.astype({'A col':'int64','B col':'int64'}).dtypes

A col    int64
B col    int64
dtype: object

In [13]:
df.astype({'A col':'int64','B col':'int64'}).dtypes

A col    int64
B col    int64
dtype: object

In [14]:
df.astype({'A col':'int64','B col':'int64'}).dtypes

A col    int64
B col    int64
dtype: object

# split data frame into two subset

In [15]:
import pandas as pd

In [8]:
import seaborn as sns
df=sns.load_dataset('titanic')
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [9]:
len(df)

891

In [23]:
df.shape

(891, 15)

In [10]:
from random import random
titanic_1=df.sample(frac=0.5)
titanic_1.shape

(446, 15)

In [11]:
from random import random
titanic_2=df.drop(titanic_1.index)
titanic_2.shape

(445, 15)

In [12]:
titanic_1.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
287,0,3,male,22.0,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True
367,1,3,female,NaN,0,0,7.2292,C,Third,woman,False,NaN,Cherbourg,yes,True
399,1,2,female,28.0,0,0,12.6500,S,Second,woman,False,NaN,Southampton,yes,True
288,1,2,male,42.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,yes,True
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True

In [13]:
titanic_2.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True

# join 2data sets

In [19]:
df1=pd.concat([titanic_1,titanic_2])
df1.shape

(891, 15)

In [20]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

#15 Filtering a dataset

In [22]:
df.sex.unique()

array(['male', 'female'], dtype=object)

In [26]:
df[(df.sex=='male')]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
883,0,2,male,28.0,0,0,10.5000,S,Second,man,True,NaN,Southampton,no,True
884,0,3,male,25.0,0,0,7.0500,S,Third,man,True,NaN,Southampton,no,True
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [27]:
df.embark_town.unique()

array(['Southampton', 'Cherbourg', 'Queenstown', nan], dtype=object)

In [29]:
df[(df.embark_town=='Southampton')]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
883,0,2,male,28.0,0,0,10.5000,S,Second,man,True,NaN,Southampton,no,True
884,0,3,male,25.0,0,0,7.0500,S,Third,man,True,NaN,Southampton,no,True
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False

In [33]:
df[(df.embark_town=='Southampton') & (df.sex=='female')]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False
10,1,3,female,4.0,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
871,1,1,female,47.0,1,1,52.5542,S,First,woman,False,D,Southampton,yes,False
880,1,2,female,25.0,0,1,26.0000,S,Second,woman,False,NaN,Southampton,yes,False
882,0,3,female,22.0,0,0,10.5167,S,Third,woman,False,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False

In [35]:
df[((df.embark_town=='Southampton') | (df.embark_town=='Cherbourg')) & (df.sex=='female')]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
879,1,1,female,56.0,0,1,83.1583,C,First,woman,False,C,Cherbourg,yes,False
880,1,2,female,25.0,0,1,26.0000,S,Second,woman,False,NaN,Southampton,yes,False
882,0,3,female,22.0,0,0,10.5167,S,Third,woman,False,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False

In [39]:
df[df.embark_town.isin(['Southampton','queenstown'])].head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True

In [42]:
df[df.age>=18].shape

(601, 15)

# 15 filtering by large categories

In [55]:
df.embark_town.value_counts().nlargest(3)

embark_town
Southampton    644
Cherbourg      168
Queenstown      77
Name: count, dtype: int64

In [56]:
df[df.who.isin(['man','woman'])].head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [60]:
counts=df.who.value_counts()

In [62]:
df[df.who.isin(counts.nlargest(2).index)].head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

#16 splitting a string into multiple columns

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
df=pd.DataFrame({'name':['Ali Ahmmad','Bilah chodary','Cippa','Danial khokhar','Ehsan ali','Farooq tradder','Ghous ahmad','H'],'location':['A1','A2','A3','B1','B2','B3','C1','C2']})
df

             name location
0      Ali Ahmmad       A1
1   Bilah chodary       A2
2           Cippa       A3
3  Danial khokhar       B1
4       Ehsan ali       B2
5  Farooq tradder       B3
6     Ghous ahmad       C1
7               H       C2

In [4]:
df.name.str.split(' ').head()

0        [Ali, Ahmmad]
1     [Bilah, chodary]
2              [Cippa]
3    [Danial, khokhar]
4         [Ehsan, ali]
Name: name, dtype: object

In [5]:
df.name.str.split(' ', expand=True)

        0        1
0     Ali   Ahmmad
1   Bilah  chodary
2   Cippa     None
3  Danial  khokhar
4   Ehsan      ali
5  Farooq  tradder
6   Ghous    ahmad
7       H     None

In [6]:

df[['first_name','last_name']]=df.name.str.split(' ', expand=True)
df

             name location first_name last_name
0      Ali Ahmmad       A1        Ali    Ahmmad
1   Bilah chodary       A2      Bilah   chodary
2           Cippa       A3      Cippa      None
3  Danial khokhar       B1     Danial   khokhar
4       Ehsan ali       B2      Ehsan       ali
5  Farooq tradder       B3     Farooq   tradder
6     Ghous ahmad       C1      Ghous     ahmad
7               H       C2          H      None

In [8]:
df[['first_name','last_name']]=df.name.str.split(' ', expand=True)
df

             name location first_name last_name
0      Ali Ahmmad       A1        Ali    Ahmmad
1   Bilah chodary       A2      Bilah   chodary
2           Cippa       A3      Cippa      None
3  Danial khokhar       B1     Danial   khokhar
4       Ehsan ali       B2      Ehsan       ali
5  Farooq tradder       B3     Farooq   tradder
6     Ghous ahmad       C1      Ghous     ahmad
7               H       C2          H      None

# 17 Aggregate by multiple groups/functions

In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
df=sns.load_dataset('titanic')
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [15]:
df.groupby('who').count()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,adult_male,deck,embark_town,alive,alone
who,,,,,,,,,,,,,,
child,83,83,83,83,83,83,83,83,83,83,13,83,83,83
man,537,537,537,413,537,537,537,537,537,537,99,537,537,537
woman,271,271,271,218,271,271,271,269,271,271,91,269,271,271

In [16]:
df.groupby('sex').count()

,survived,pclass,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
sex,,,,,,,,,,,,,,
female,314,314,261,314,314,314,312,314,314,314,97,312,314,314
male,577,577,453,577,577,577,577,577,577,577,106,577,577,577

In [24]:
len(df.groupby('who'))

3

In [25]:
df.groupby('who').count()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,adult_male,deck,embark_town,alive,alone
who,,,,,,,,,,,,,,
child,83,83,83,83,83,83,83,83,83,83,13,83,83,83
man,537,537,537,413,537,537,537,537,537,537,99,537,537,537
woman,271,271,271,218,271,271,271,269,271,271,91,269,271,271

# Select specific rows and columns